### ISSUE TITLE
Support ClassTests as Test class name

### ISSUE THREAD

**Issue by Clindbergh** [MatWein/UnitVisualizer#2]
In our project the test class is not called *Test, but *Tests. It would be nice, if these classes were found as well.

---

I am willing to implement this functionality (by extending the TestClassDetector class) and submit a PR. Please let me know if you're open to include the functionality in your plugin.

**Comment by MatWein** [comment]
Hi Clindbergh,

thanks for your request. I think this change is small and brings an advantage, so I decided to take over your pull request but with small "cosmetic" changes. It will be available with release 1.7.1 which should be available in the next few days after JetBrains approval. Thanks for your time and work!

**Comment by Clindbergh** [comment]
Thanks for merging and releasing so quickly 👍 .

**Comment by Clindbergh** [comment]
I noticed there is also a setting for Code Generation to determine Test names. It might be even better to use these settings too.

![grafik](https://user-images.githubusercontent.com/2742027/152822305-7fc92264-9b8a-4633-bc5c-fb8c535b817e.png)
