### ISSUE TITLE
Support for moving Groovy tests

### ISSUE THREAD

**Issue by ruedigerk** [MatWein/UnitVisualizer#5]
Hello,

my tests are written in Groovy using the Spock framework. This also means that the tests are in the src/test/groovy source root. Unfortunately, the plugin does not move these Groovy test classes when the associated Java class is moved. Could you please have a look at this? Maybe the plugin is only looking for Java classes when searching for the associated test class?

Interestingly, the icon decorations are working properly for the Groovy tests. Even the Groovy test methods are properly recognized, although they often have names not matching the tested methods' names.

Tested with IntelliJ 2021.3.3 and UnitVisualizer 1.7.1

**Comment by MatWein** [comment]
Hey ruedigerk,

could you please provide an example project where you can reproduce the problem?

**Comment by ruedigerk** [comment]
I attached a simple Maven project that you can import as a new project into IntelliJ that shows the problem. Actually, in that project neither the Java test class nor the Groovy test class is moved together with their respective main classes.

<img width="307" alt="grafik" src="https://user-images.githubusercontent.com/875477/163401470-a14a88a5-db7d-4cd9-9b55-7962247e3f35.png">

[unit-visualizer-repro.zip](https://github.com/MatWein/UnitVisualizer/files/8489501/unit-visualizer-repro.zip)

Thank you for having a look at this!

**Comment by MatWein** [comment]
Thanks for providing an example project. I added support for moving groovy classes in 1.7.2. It can take several days until JetBrains has approved the new version.

**Comment by ruedigerk** [comment]
Thank you very much!

**Comment by ruedigerk** [comment]
I just tested this with the new version 1.7.2 and it works as expected. Very nice! :)
